### PR TITLE
Config page refactor  + Fix for small screens

### PR DESCRIPTION
**Pull request by marcteys**
I made a huge refactor on the config page.
Now the .css style and .js files in folders, nothing fancy.

I have made a quick-fix for the display on small-size devices : if the container `preview` is bigger than half of the page height, then remove the `fixed` attribute. Simple and working. 

Side Note : I am not (yet) familiar with reactiveJS. I think's it's way too much complicated for a simple static page. A custom solution will be easier to manage, understand and will be more flexible and stable. But i'm not sure I am motivated enough to refactor everything, so I'll stay with that for now. ^^

### CODE REVIEW

**Comment by groyoh** [comment]
Yeah, as I said I have barely no knowledge about frontend, came across Ractive once and decided to try it out. But I might drop it out in the future.

**Comment by marcteys** [comment]
@groyoh  I definitely read in your code that you are more a backend/hardcore guy :D I'll try to do a simpler  design pattern for the config page

**Comment by Spitemare** [comment]
Normally separating your CSS and JS from your HTML is a good thing. Ractive, however, encourages keeping them all together because it's not really HTML but a Ractive component. Everything that describes the component, from layout to behavior to styling, can be self contained. In flies in the face of traditional conventions, but it is a fine idea in a component based framework.

More importantly, Ractive automatically namespaces CSS rules per component so you don't have to worry about how rules from one component might affect another.

**Comment by marcteys** [comment]
Reactivejs is way too much for a single front-end page file imho. And for an open-source project, it might be better to build something more flexible which grant collaboration.

I am working on a new version, refactored ans without reactive. @groyoh are you ok with that, should I continue?

**Comment by Spitemare** [comment]
Don't mistake [Ractive](http://www.ractive.org) with [React](
https://facebook.github.io/react/). I agree that React is way too much for
this app. Ractive, though, provides data binding (which is used heavily in
the SVG) in a small package with minimal overhead. The fact that components
come free is a bonus.

**Comment by groyoh** [comment]
@marcteys It depends on what you plan to do. If the configuration is easy to handle afterward, I'd probably not say no. Right now it may not be the nicest but it works pretty fine and I'd rather keep it as it is if changing it doesn't bring too much advantages.

@Spitemare @marcteys I actually like the way Ractive handles components. One thing that I disliked was that it's actually quite heavy and a bit slow to load. That works fine on computer but on mobile it kind of sucks.

@marcteys Also keep in mind that open-source does not always mean collaboration :wink:

**Comment by marcteys** [comment]
I agree with you on the heavy load of reactive. I think that's what I dislike. I plan to do a lightweight templating system, with a easy event manager. I actually already did it for other pebble configuration pages.

I hope your vision of open source means collaboration. ;) In my opinion it doesn't really make sense to share a project in open-source while not let other to share their knowledge and improve the project. (At least that's my vision of open source )

**Comment by groyoh** [comment]
@marcteys could you maybe point to these project so that I can have a look? Would be easier for me to judge whether it's worth the work or not. Thanks!

> I hope your vision of open source means collaboration. émoticône wink In my opinion it doesn't really make sense to share a project in open-source while not let other to share their knowledge and improve the project. (At least that's my vision of open source )

Minimalin is open-source mainly because we (@AlessioLaiso and I) did not see any benefit in doing it any other way. We really like Pebble, we wanted to build our dream watchface and we had a lot of fun working on it. We did not plan to earn money from it and having it open-source means that other people can benefit from it (have their own modified version, build their own watchface on top of it, etc.). This is my vision of open-source. Collaboration is just one outcome of the open-source model, that of course can be awesome and really helpful.

**Comment by marcteys** [comment]
I'll do a structure a little bit like https://github.com/marcteys/pixebble 

For the config page it will look like that:
* Top-Left : index.html . Calling the JS file, sme public "config" variables
* Top-Right : Sample of the JS structure. I'll build some JS files for each components with easy to understand/edit functions.
* Bottom-Left : style.css
* Bottom-Right : A sample of the templating system. Mostly similar with what you are using now. (Injecting variables in the {{}}, then injecting templates in the DOM) 

untitled-1

To sum-up : Independents components and lightweight structure :-)

**Comment by groyoh** [comment]
@marcteys Sorry for the delay, I was on holidays.

What library do you use for template injection? Is it custom-made? Is it a two-way binding? I'm not sure if this is actually needed at the moment as the configuration page is not really got change that much.

Also I do not like the fact that the css part were extracted into a CSS file. Having some css inside a component is part of Ractive way of building things. There was actually a plan to extract Slate css into the components but I never really had time to do it.

**Pull request closed without merging**
